import { Stage } from "../master/stage/stage";
import { Compliance } from "../master/compliance/compliance";

export interface Institution {
  institutionName:string,
  branch:string,
  reportType:string,
  uploadCases:string,
  uploadCaseFiles:string,
  caseId:number,
  stage:string,
  courtCaseId:number,
  legalCaseId:number,
  lastHearingDate:Date,
  nextHearingDate:Date,
  loanAccountNumber:number,
  compliance : string,
  recourse: string,
  region : string,
  location : string,
  productGroup : string,
  customerName :string,
  DPDAsOnFilingDate : number,
  dateOfFilingCase : Date,
  courtPlace : string,
  lawyerName : string,
  stageInCourt : string,
  orderReceivedDate : string,
  rOStatus : string,
  arbitrationInitiated : string,
  repoFlag : string,
  legalManager : string,
  closureDate : Date,
  totalAmtRecovered : number,
  caseFiledAgainst : string,
  DPDAsOnCurrentSystemDate : number,
  caseCriticalityLevel : string,
  parentID : number,
  generatedBy : string,
  uploadDocument : string,
  groundForClosingFile : string,
  disposedOffFileNo : number,
  state : string,
  product : string,
  POSAsOnFilingDate : Date,
  NPAStageAsOnFilingDate : Date,
  caseType : string,
  courtName : string,
  amountInvolved : number,
  caseStage : string,
  previousHearingDate : Date,
  NDOHNullReason : string,
  receiverName : string,
  ROExecutionDate : Date,
  arbitrationcaseID : number,
  remarks : string,
  caseStatus : string,
  closureReportingDate : Date,
  accountStatus : string,
  POSAsOnCurrentSystemDate : number,
  NPAStageAsOnCurrentSystemDate : string,
  type : string,
  childCase : string,
  completionDate: Date,
  id: number
}